# Generated by Django 4.1.3 on 2022-11-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=30)),
                ('arrivee', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('heure', models.CharField(max_length=15)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.trajet')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('vols', models.ManyToManyField(to='reservation.vol')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
